let arrLang = {
    cz: {
        'planetsH1': 'Planety',
        'infoScaleFactorScene': 'Model má upravenou velikost pro přehlednější zobrazení. Zmenšené objekty: Slunce 27x, Jupiter a Saturn 6x, Uran a Neptun 5x. Rozměry orbit jsou také zmenšeny vzhledem k modelu.',
        // <title>
        'simulator': 'Simulátor sluneční soustavy',
        'infoPage': 'Informace',
        'planets': 'Planety',
        'planetMercury': 'Planeta Merkur',
        'planetVenus': 'Planeta Venuše',
        'planetEarth': 'Planeta Země',
        'planetMars': 'Planeta Mars',
        'planetJupiter': 'Planeta Jupiter',
        'planetSaturn': 'Planeta Saturn',
        'planetUranus': 'Planeta Uran',
        'planetNeptune': 'Planeta Neptun',
        // Menu
        'ssm': 'Model sluneční soustavy',
        'planets': 'Planety',
        'about': 'O aplikaci',
        // Sidebar
        'names': 'Jména',
        'allPlanets': 'Pro všechny planety',
        'singlePlanet': 'Pro planetu',
        'allMoons': 'Pro všechny měsíce',
        'singleMoon': 'Pro měsíc',
        'earthMoon': 'Měsíc',
        'allMoonsObjectsOfSinglePlanet': 'Měsíce planety',
        'moonsTable': 'Měsíce',
        'allMoonsObjects': 'Všechny měsíce',
        'orbit': 'Orbita',
        'velocity': 'Rychlost',
        'newValue': 'Nová hodnota',
        'mercury': 'Merkur',
        'venus': 'Venuše',
        'earth': 'Země',
        'uranus': 'Uran',
        'neptune': 'Neptun',
        'confirm': 'Potvrdit',
        // Sidebar - planet physical info
        'physicalValuesPlanet': 'Fyzikální vlastnosti planety',
        'physicalValuesMoon': 'Fyzikální vlastnosti měsíce',
        'planetMass': 'Hmotnost planety:',
        'diameter': 'Rovníkový poloměr (km):',
        'perimeter': 'Obvod planety (km):',
        'rotationSpeed': 'Rychlost rotace na orbitě (km/s):',
        'rotationPeriod': 'Oběžná doba kolem své osy (hod): ',
        'orbitalPeriod': 'Oběžná doba kolem Slunce (dny): ',
        'distanceFromSunPerihelion': 'Vzdálenost od Slunce - Perihelion:',
        'distanceFromSunAphelion': 'Vzdálenost od Slunce - Aphelion:',
        'negativeRotationPeriodMeaning': 'Čas 1 rotace planety vzhledem ke fixnnímu pozadí hvězd, ne ke Slunci. Záporní hodnota představuje spátoční rotaci (opačný směr ve srovnání se Zemí).',
        'orbitalPeriodMeaning': 'Čas v dnech Země, za který planeta oběhne kolem Slunce a přejde z jedné jarní rovnodennosti na druhou.',
        'distanceFromSunMeaning': 'Průměrná vzdálenot od planety ke Slunci v milionech kilometrů, známá také jako "semi-major" os.',
        'perihelionMeaning': 'Nejbližší bod na orbitě planety kolem Slunce, hodnota je v milionech kilometrů.',
        'aphelionMeaning': 'Nejvzdálenější bod na orbitě planety kolem Slunce, hodnota je v milionech kilometrů.',
        // Sidebar - moon physical info
        'moonMass': 'Hmotnost měsíce:',
        'orbitalPeriodMoon': 'Oběžná doba kolem planety (dny):',
        'distanceFromPlanet': 'Vzdálenost od planety (km):',
        'minTemperature': 'Minimální teplota:',
        'maxTemperature': 'Maximální teplota:',
        // Rangesliders and buttons
        'changeOrbit': 'Změna dráhy působením rychlosti: ',
        'zoom': 'Přiblížení: ',
        'centerModel': 'Vycentrovat',
        'cosmicObject': 'Kosmický objekt',
        'cameraToPlanet': 'Kamera na planetu',
        // Planets
        'backToPlanets': 'Zpátky na planety',
        // Translation for long text (pages for planets)
        'mercuryText': 'Merkur je planeta nejbližší ke Slunci. Na každé dvě oběžné dráhy Slunce absolvuje Merkur tři rotace kolem své osy. Třináctkrát za století lze pozorovat Merkur ze Země procházející kolem Slunce. Tato událost se nazývá tranzit.',
        'venusText': 'Venuše je druhou planetou od Slunce a je druhou největší suchozemskou planetou. Venuše se pro svou podobnou velikost a hmotnost někdy označuje jako sesterská planeta Země. Venuše je pojmenovaná po římské bohyni lásky a krásy.',
        'earthText': 'Země je třetí planetou od Slunce a je největší ze suchozemských planet. Země je jedinou planetou v naší sluneční soustavě, která není pojmenována podle řeckého nebo římského božství. Zemi vznikla asi před 4,54 miliardami let a je jedinou známou planetou, která podporuje život.',
        'marsText': 'Mars je čtvrtá planeta od Slunce a je druhou nejmenší planetou ve sluneční soustavě. Mars, pojmenovaný podle římského boha války, je kvůli načervenalý vzhledu také často označován jako "Červená planeta". Mars je suchozemská planeta s řídkou atmosférou složenou především z oxidu uhličitého.',
        'jupiterText': 'Jupiter je největší planetou ve sluneční soustavě a je pátou planetou od Slunce. Je dvaapůlkrát hmotnější než všechny ostatní planety ve sluneční soustavě dohromady. Primární je tvořen z plynů, a proto je známý jako "plynový gigant".',
        'saturnText': 'Saturn, který je nejlépe známý díky svému pohádkovému prstencová systému, je šestou planetou od Slunce a druhou největší v naší sluneční soustavě. Stejně jako Jupiter, i Saturn je plynný gigant a je složen z podobných plynů včetně vodíku, hélia a metanu.',
        'uranusText': 'Uran je sedmá planeta od Slunce. Není viditelná pouhým okem a stala se první planetou objevenou pomocí dalekohledu. Uran je převrácený na své straně s axiálním sklonem 98 stupňů. Často se to popisuje jako "valení se kolem Slunce na jeho boku".',
        'neptuneText': 'Neptun je osmou planetou od Slunce, díky čemuž je nejvzdálenější ve sluneční soustavě. Tento plynný gigant mohl v ranní historii sluneční soustavy zformovat mnohem blíže ke Slunci, než se dostal do své současné polohy.',
        // Page About - headings
        'howToUseApplication': 'Jak používat aplikaci',
        'menuFunctionality': 'Funkcionalita menu',
        'menuSolarSystemModelHeading': 'Model sluneční soustavy',
        'menuPlanetsHeading': 'Planety',
        'rightSidebar': 'Pravý boční panel',
        '3buttons': '3 tlačítka (v levém dolním rohu)',
        'zoomRangeslider': 'Posuvník na přiblížení modelu',
        'moveModelFunctions': 'Funkce pro posouvání modelu',
        'clickOnSceneObjects': 'Klikání na objekty',
        'sidebarOpenCloseHeading': 'Otevření a zavření bočního panelu:',
        'sidebarObjectNamesHeading': 'Jména vesmírných objektů:',
        'sidebarMoonObjectsHeading': 'Měsíce:',
        'sidebarObjectOrbitsHeading': 'Orbity vesmírných objektů:',
        'sidebarPlayPauseButtonsHeading': 'Tlačítko pro zastavení/spuštění aplikace:',
        'sidebarConfirmButtonHeading': 'Tlačítko "Potvrdit":',
        'cosmicObjectButtonHeading': 'Tlačítko pro kosmický objekt:',
        'cameraToPlanetButtonHeading': 'Tlačítko pro kameru:',
        'centerModelButtonHeading': 'Tlačítko pro vycentrování modelu:',
        // Page About - text
        'menuSolarSystemModelInfo': 'V případě, že je model zobrazený v aktuálním okně, výběrem položky "Model sluneční soustavy" se zobrazí upozornění o ztrátě všech nastavených vlastností pro model. Po akceptování změn bude model znovu načten do původního stavu. Po zamítnutí změn zůstane otevřený aktuální model. Otevření modelů ve více oknech webového prohlížeče bude zamítnuto pro menší zatížení prohlížeče.',
        'menuPlanetsInfo': 'Výběrem položky "Planety" se otevře nová záložka s nabídkou planet. Po výběru a kliknutí na jednu planetu se zobrazí stránka se stručným popisem a interaktivním modelem planety, který je možné ovládat kurzorem.',
        'cosmicObjectButtonInfo': 'Kliknutím na tlačítko je možné přidat 1 umělý kosmický objekt na orbitu poslední vybrané planety. Pokud uživatel zatím nekliknul na žádnou planetu, po aktivaci tlačítka je třeba vybranou planetu označit kliknutím na ni nebo její orbitu. Přidání objektu dočasně skryje zobrazeny měsíce zvolené planety kvůli přehlednějšímu zobrazení. Během aktivního stavu tlačítka jsou dočasně nefunkční funkce klikání na objekty a zobrazení jejich fyzikálních vlastností. Aktivní tlačítko zpřístupní posuvník (v horní části obrazovky), který slouží ke změně dráhy kosmického objektu. Je znázorněna i změna rychlosti pohybu podle vzdálenosti objektu od planety. Deaktivaci tlačítka lze provést pomocí jeho opětovného stlačení, projeví se změnou barvy.',
        'cameraToPlanetButtonInfo': 'Kliknutím na tlačítko je možné přiblížit kameru na poslední vybranou planetu. Výběr planety funguje stejně jako u tlačítka pro kosmický objekt. Přiblížení kamery nabízí bližší pohled na vesmírné těleso a jeho měsíce. Narozdíl od přiblížení celého modelu kamera následuje zvolený objekt při rotací po orbitě. Během aktivního stavu tlačítka jsou přístupné funkce klikání na objekty a zobrazení jejich fyzikálních vlastností. Deaktivaci tlačítka lze provést pomocí jeho opětovného stlačení, projeví se změnou barvy.',
        'centerModelButtonInfo': 'Kliknutím na tlačítko se posune model do středu obrazovky. V případě, že modelem nebylo pohybováno pomocí kurzoru nebo šipek na klávesnici, model zůstane na stejném místě.',
        'zoomRangesliderInfo': 'Přiblížení či zmenšení modelu lze provést pomocí posuvníku umístěného uprostřed obrazovky dole. Pokud bude zvolena velikost modelu menší než 70%, měsíce planet budou dočasně skryté z důvodu malé velikosti modelu.',
        'moveModelFunctionsInfo': 'Pohybování modelu lze provést pomocí kliknutí na libovolné místo obrazovky (kromě objektů modelu) a potažením pomocí kurzoru. Další možností je využití šipek na klávesnici. Vrácení modelu na původní pozici je možné pomocí tlačítka na vycentrování modelu nebo klávesou Escape.',
        'clickOnSceneObjectsInfo': 'Model je rozšířen o možnost klikání na jednotlivé planety, měsíce nebo jejich orbity. Kliknutím na vesmírný objekt nebo jeho orbitu se v levé části obrazovky zobrazí tabulka s vybranými fyzikálními vlastnostmi a údaji o zvoleném tělese. Pro odlišení je vybraný objekt i jeho orbita barevně odlišen. Údaje v tabulce jsou dostupné pouze pro čtení, tabulka je doplněna o info bubliny pro vysvětlení vybraných fyzikálních vlastností, které reagují na umístění kurzoru nad nimi. Zavření tabulky je možné pomocí kliknutí na libovolné místo v tabulce.',
        'sidebarOpenCloseInfo': 'Ovládání funguje pomocí ikony umístěné nad panelem. Kliknutím na ikonu se panel zavře/otevře.',
        'sidebarObjectNamesInfo': 'Pro zobrazení pouze 1 jména pro planetu nebo měsíc je třeba zrušit možnost zobrazení všech jmen, vybrat z nabídky konkrétní jméno a potvrdit volbu tlačítkem "Potvrdit".',
        'sidebarMoonObjectsInfo': 'V nabídce jsou možnosti zobrazení všech měsíců, skrytí všech měsíců nebo zobrazení měsíců pro zvolenou planetu. Zobrazení jmen a orbit měsíců závisí od ostatních voleb v postranním panelu. Volbu je třeba potvrdit tlačítkem "Potvrdit". Měsíce mohou být zobrazeny pouze do velikosti modelu, který je přiblížen na minimálně 70%.',
        'sidebarObjectOrbitsInfo': 'Pro zobrazení pouze 1 orbity pro planetu nebo měsíc je třeba zrušit možnost zobrazení všech orbit, vybrat z nabídky konkrétní planetu nebo měsíc, pro kterou bude zobrazena orbita a potvrdit volbu tlačítkem "Potvrdit".',
        'sidebarPlayPauseButtonsInfo': 'Tlačítko zastaví pohyb planet a měsíců na oběžných drahách. Ostatní funkce jsou stále přístupné i během pozastavení pohybu vesmírných objektů.',
        'sidebarConfirmButtonInfo': 'Tlačítko slouží k potvrzení a provedení všech zvolených možností v postranním panelu. Po jeho stisknutí bude tlačítko dočasně nefunkční, dokud se provedou všechny změny.'
    },
    en: {
        'planetsH1': 'Planets',
        'infoScaleFactorScene': 'The model is scaled for a clearer view. Scale objects: Sun 27x, Jupiter and Saturn 6x, Uranus and Neptune 5x. The dimensions of the orbits are also reduced with respect to the model.',
        // <title>
        'simulator': 'Solar system simulator',
        'infoPage': 'Information',
        'planets': 'Planets',
        'planetMercury': 'Planet Mercury',
        'planetVenus': 'Planet Venus',
        'planetEarth': 'Planet Earth',
        'planetMars': 'Planet Mars',
        'planetJupiter': 'Planet Jupiter',
        'planetSaturn': 'Planet Saturn',
        'planetUranus': 'Planet Uranus',
        'planetNeptune': 'Planet Neptune',
        // Menu
        'ssm': 'Solar system model',
        'planets': 'Planets',
        'about': 'About application',
        // Sidebar
        'names': 'Names',
        'allPlanets': 'For all planets',
        'singlePlanet': 'For single planet',
        'allMoons': 'For all moons',
        'singleMoon': 'For single moon',
        'earthMoon': 'Moon',
        'allMoonsObjectsOfSinglePlanet': 'Moons of planet',
        'moonsTable': 'Moons',
        'allMoonsObjects': 'All moons',
        'orbit': 'Orbit',
        'velocity': 'Velocity',
        'newValue': 'New value',
        'mercury': 'Mercury',
        'venus': 'Venus',
        'earth': 'Earth',
        'uranus': 'Uranus',
        'neptune': 'Neptune',
        'confirm': 'Confirm',
        // Sidebar - planet physical info
        'physicalValuesPlanet': 'Physical values of planet',
        'physicalValuesMoon': 'Physical values of moon',
        'planetMass': 'Weight of planet:',
        'diameter': 'Equatorial diameter (km):',
        'perimeter': 'Perimeter of planet (km):',
        'rotationSpeed': 'Rotation speed on orbit (km/s):',
        'rotationPeriod': 'Rotation period around its axis (h): ',
        'orbitalPeriod': 'Orbital period around Sun (days): ',
        'distanceFromSunPerihelion': 'Distance from Sun - Perihelion:',
        'distanceFromSunAphelion': 'Distance from Sun - Aphelion:',
        'negativeRotationPeriodMeaning': "Time of 1 planet's rotation relative to the fixed background stars, not to the Sun. Negative numbers indicate retrograde rotation (backwards relative to the Earth).",
        'orbitalPeriodMeaning': 'Time in Earth days for a planet to orbit the Sun from one vernal equinox to the next.',
        'perihelionMeaning': "The closest point on planet's orbit around Sun, value is in millions of kilometers.",
        'aphelionMeaning': "The furthest point on planet's orbit around Sun, value is in millions of kilometers.",
        // Sidebar - moon physical info
        'moonMass': 'Weight of moon:',
        'orbitalPeriodMoon': 'Orbital period around planet (days):',
        'distanceFromPlanet': 'Distance from planet (km):',
        'minTemperature': 'Minimum temperature:',
        'maxTemperature': 'Maximum temperature:',
        // Rangesliders and buttons
        'changeOrbit': 'Change orbit by speed: ',
        'zoom': 'Zoom: ',
        'centerModel': 'Center model',
        'cosmicObject': 'Cosmic object',
        'cameraToPlanet': 'Camera to planet',
        // Planets
        'backToPlanets': 'Back to planets',
        // Translation for long text (pages for planets)
        'mercuryText': 'Mercury is the closest planet to the Sun. For every two orbits of the Sun, Mercury completes three      rotations about its axis. Thirteen times a century Mercury can be observed from the Earth passing across the face of the Sun in an event called a transit.',
        'venusText': 'Venus is the second planet from the Sun and is the second largest terrestrial planet. Venus is sometimes referred to as the Earth’s sister planet due to their similar size and mass. Venus is named after the Roman goddess of love and beauty.',
        'earthText': 'Earth is the third planet from the Sun and is the largest of the terrestrial planets. The Earth is the only planet in our solar system not to be named after a Greek or Roman deity. The Earth was formed approximately 4.54 billion years ago and is the only known planet to support life.',
        'marsText': 'Mars is the fourth planet from the Sun and is the second smallest planet in the solar system. Named after the Roman god of war, Mars is also often described as the “Red Planet” due to its reddish appearance. Mars is a terrestrial planet with a thin atmosphere composed primarily of carbon dioxide.',
        'jupiterText': 'Jupiter is the largest planet in the solar system and is the fifth planet out from the Sun. It is two and a half times more massive than all the other planets in the solar system combined. It is made primarily of gases and is therefore known as a “gas giant”.',
        'saturnText': 'Best known for its fabulous ring system, Saturn is the sixth planet from the Sun and the second largest in our solar system. Like Jupiter, Saturn is a gas giant and is composed of similar gasses including hydrogen, helium and methane.',
        'uranusText': 'Uranus is the seventh planet from the Sun. It’s not visible to the naked eye, and became the first planet discovered with the use of a telescope. Uranus is tipped over on its side with an axial tilt of 98 degrees. It is often described as “rolling around the Sun on its side.”',
        'neptuneText': 'Neptune is the eighth planet from the Sun, making it the most distant in the solar system. This gas giant may have formed much closer to the Sun in the early solar system history before migrating out to its current position.',
        // Page About - headings
        'howToUseApplication': 'How to use application',
        'menuFunctionality': 'Functionality of menu',
        'menuSolarSystemModelHeading': 'Solar system model',
        'menuPlanetsHeading': 'Planets',
        'rightSidebar': 'Right side panel',
        '3buttons': '3 buttons (at the bottom left corner)',
        'zoomRangeslider': 'Slider for zooming model',
        'moveModelFunctions': 'Functions for shifting model',
        'clickOnSceneObjects': 'Click on objects',
        'sidebarOpenCloseHeading': 'Opening and closing the sidebar:',
        'sidebarObjectNamesHeading': 'Names of space objects:',
        'sidebarMoonObjectsHeading': 'Moons:',
        'sidebarObjectOrbitsHeading': 'Orbits of space objects:',
        'sidebarPlayPauseButtonsHeading': 'Application Pause/Play button:',
        'sidebarConfirmButtonHeading': '"Confirm" button:',
        'cosmicObjectButtonHeading': 'Cosmic object button:',
        'cameraToPlanetButtonHeading': 'Camera button:',
        'centerModelButtonHeading': 'Model centering button:',
        // Page About - text
        'menuSolarSystemModelInfo': 'If the model is displayed in the current window, selecting the "Solar system model" item will display a notification about the loss of all set properties for the model. After accepting the changes, the model will be reloaded to its original state. After rejecting the changes, the current model will remain open. Opening models in multiple web browser windows will be denied to reduce browser load.',
        'menuPlanetsInfo': 'Selecting item "Planets" will open a new tab with a menu of planets. After selecting and clicking on one planet, a page will appear with a brief description and an interactive model of the planet, which can be controlled by the cursor.',
        'cosmicObjectButtonInfo': 'By clicking on the button it is possible to add single artificial cosmic object to the orbit of the last selected planet. If the user has not yet clicked on any planet, after activating the button, the selected planet must be marked by clicking on it or its orbit. Adding an object temporarily hides the displayed moons of the selected planet for a clearer view. During the active state of the button, the functions for clicking on objects and displaying their physical properties are temporarily inactive. The active button accesses the slider (at the top of the screen), which is used to change the path of the space object. The change of rotation speed is also shown, according to the distance of the object from the planet. Deactivation of the button can be done by pressing it again, it will show a change in color.',
        'cameraToPlanetButtonInfo': 'By clicking on the button it is possible to zoom the camera to the last selected planet. Selecting a planet works the same as with the cosmic object button. Zooming in on the camera offers a closer look at the planet and its moons. Unlike zooming in on the entire model, the camera follows the selected object during rotation on its orbit. During the active state of the button, the functions for clicking on objects and displaying their physical properties are accessible. Deactivation of the button can be done by pressing it again, it will be reflected in a color change.',
        'centerModelButtonInfo': 'By clicking on the button the model willl move to the center of the screen. If the model has not been moved with the cursor or arrows on the keyboard, the model will remain in the same place.',
        'zoomRangesliderInfo': "Zoom in or out on the model can be done using the slider located in the bottom middle of the screen. If the selected model size is less than 70%, the planet's moons will be temporarily hidden due to the small model size.",
        'moveModelFunctionsInfo': 'Moving the model is possible by clicking anywhere on the screen (except model objects) and dragging with the cursor. Another option is to use the arrows on the keyboard. Returning the model to its original position is possible by using the model centering button or the Escape key.',
        'clickOnSceneObjectsInfo': 'The model is extended by the possibility of clicking on individual planets, moons or their orbits. Clicking on a cosmic object or its orbit will display a table on the left side of the screen with selected physical properties and data about the selected body. To distinguish, the selected object and its orbit are color-coded. The data in the table are read-only, the table is supplemented with info bubbles to explain selected physical properties that respond to the cursor position above them. Closing the table is possible by clicking anywhere in the table.',
        'sidebarOpenCloseInfo': 'The control works with an icon located above the panel. Click on the icon will close/open the panel.',
        'sidebarObjectNamesInfo': 'To display only single name for a planet or moon, it is necessary to cancel the option of displaying all names, select a specific name from the menu and confirm the selection with the "Confirm" button.',
        'sidebarMoonObjectsInfo': 'In the sidebar there are options to show all moons, hide all moons or show moons for the selected planet. The display of names and orbits of the moons depends on the other chosen options in the sidebar. The selection must be confirmed with the "Confirm" button. The moons can only be displayed up to the size of the model, which is zoomed in at least 70%.',
        'sidebarObjectOrbitsInfo': 'To display only single orbit for a planet or moon, it is necessary to cancel the option of displaying all orbits, select a specific planet or moon for which the orbit will be displayed and confirm the selection with the "Confirm" button.',
        'sidebarPlayPauseButtonsInfo': 'Pause button stops the movement of planets and moons on orbits. Other functions are still accessible even while space objects are paused.',
        'sidebarConfirmButtonInfo': 'The button is used to confirm and execute all selected options in the sidebar. When pressed, the button will temporarily not work until all changes have been made.'
    },
    sk: {
        'planetsH1': 'Planéty',
        'infoScaleFactorScene': 'Model má upravenú mierku pre prehľadnejšie zobrazenie. Zmenšené objekty: Slnko 27x, Jupiter a Saturn 6x, Urán a Neptún 5x. Rozmery orbít sú tiež zmenšené vzhľadom k modelu.',
        // <title>
        'simulator': 'Simulátor slnečnej sústavy',
        'infoPage': 'Informácie',
        'planets': 'Planéty',
        'planetMercury': 'Planéta Merkúr',
        'planetVenus': 'Planéta Venuša',
        'planetEarth': 'Planéta Zem',
        'planetMars': 'Planéta Mars',
        'planetJupiter': 'Planéta Jupiter',
        'planetSaturn': 'Planéta Saturn',
        'planetUranus': 'Planéta Urán',
        'planetNeptune': 'Planéta Neptún',
        // Menu
        'ssm': 'Model slnečnej sústavy',
        'planets': 'Planéty',
        'about': 'O aplikácii',
        // Sidebar
        'names': 'Mená',
        'allPlanets': 'Pre všetky planéty',
        'singlePlanet': 'Pre planétu',
        'allMoons': 'Pre všetky mesiace',
        'singleMoon': 'Pre mesiac',
        'earthMoon': 'Mesiac',
        'allMoonsObjectsOfSinglePlanet': 'Mesiace planéty',
        'moonsTable': 'Mesiace',
        'allMoonsObjects': 'Všetky mesiace',
        'orbit': 'Orbita',
        'velocity': 'Rýchlosť',
        'newValue': 'Nová hodnota',
        'mercury': 'Merkúr',
        'venus': 'Venuša',
        'earth': 'Zem',
        'uranus': 'Urán',
        'neptune': 'Neptún',
        'confirm': 'Potvrdiť',
        // Sidebar - planet physical info
        'physicalValuesPlanet': 'Fyzikálne vlastnosti planéty',
        'physicalValuesMoon': 'Fyzikálne vlastnosti mesiaca',
        'planetMass': 'Hmotnosť planéty:',
        'diameter': 'Rovníkový polomer (km):',
        'perimeter': 'Obvod planéty (km):',
        'rotationSpeed': 'Rýchlosť rotácie na orbite (km/s):',
        'rotationPeriod': 'Čas obehu okolo svojej osi (hod): ',
        'orbitalPeriod': 'Čas obehu okolo Slnka (dni): ',
        'distanceFromSunPerihelion': 'Vzdialenosť od Slnka - Perihelion:',
        'distanceFromSunAphelion': 'Vzdialenosť od Slnka - Aphelion:',
        'negativeRotationPeriodMeaning': 'Čas 1 rotácie planéty vzhľadom ku fixnému pozadiu hviezd, nie ku Slnku. Záporná hodnota predstavuje spiatočnú rotáciu (opačný smer v porovnaní so Zemou).',
        'orbitalPeriodMeaning': 'Čas v dňoch Zem, za ktorý planéta obehne okolo Slnka a prejde z jednej jarnej rovnodennosti na druhú.',
        'perihelionMeaning': 'Najbližší bod na orbite planéty okolo Slnka, hodnota je v miliónoch kilometrov.',
        'aphelionMeaning': 'Najvzdialenejší bod na orbite planéty okolo Slnka, hodnota je v miliónoch kilometrov.',
        // Sidebar - moon physical info
        'moonMass': 'Hmotnosť mesiaca:',
        'orbitalPeriodMoon': 'Čas obehu okolo planéty (dni):',
        'satelliteOfPlanet': 'Satelit planéty:',
        'distanceFromPlanet': 'Vzdialenosť od planéty (km):',
        'minTemperature': 'Minimálna teplota:',
        'maxTemperature': 'Maximálna teplota:',
        // Rangesliders and buttons
        'changeOrbit': 'Zmena dráhy pôsobením rýchlosti: ',
        'zoom': 'Priblíženie: ',
        'centerModel': 'Vycentrovať',
        'cosmicObject': 'Kozmický objekt',
        'cameraToPlanet': 'Kamera na planétu',
        // Planets
        'backToPlanets': 'Späť na planéty',
        // Translation for long text (pages for planets)
        'mercuryText': 'Merkúr je planéta najbližšia k Slnku. Na každé dve obežné dráhy Slnka absolvuje Merkúr tri rotácie okolo svojej osi. Trinásťkrát za storočie je možné pozorovať Merkúr zo Zeme prechádzajúcej okolo Slnka. Táto udalosť sa nazýva tranzit.',
        'venusText': 'Venuša je druhou planétou od Slnka a je druhou najväčšou suchozemskou planétou. Venuša sa pre svoju podobnú veľkosť a hmotnosť niekedy označuje ako sesterská planéta Zeme. Venuša je pomenovaná po rímskej bohyni lásky a krásy.',
        'earthText': 'Zem je treťou planétou od Slnka a je najväčšou zo suchozemských planét. Zem je jedinou planétou v našej slnečnej sústave, ktorá nie je pomenovaná podľa gréckeho alebo rímskeho božstva. Zem vznikla asi pred 4,54 miliardami rokov a je jedinou známou planétou, ktorá podporuje život.',
        'marsText': 'Mars je štvrtá planéta od Slnka a je druhou najmenšou planétou v slnečnej sústave. Mars, pomenovaný podľa rímskeho boha vojny, je kvôli červenkastému vzhľadu tiež často označovaný ako „Červená planéta“. Mars je suchozemská planéta s riedkou atmosférou zloženou predovšetkým z oxidu uhličitého.',
        'jupiterText': 'Jupiter je najväčšou planétou v slnečnej sústave a je piatou planétou od Slnka. Je dva a polkrát hmotnejšia ako všetky ostatné planéty v slnečnej sústave dokopy. Primárne je tvorený z plynov, a preto je známy ako „plynový gigant“.',
        'saturnText': 'Saturn, ktorý je najlepšie známy vďaka svojmu rozprávkovému prstencovému systému, je šiestou planétou od Slnka a druhou najväčšou v našej slnečnej sústave. Rovnako ako Jupiter, aj Saturn je plynný gigant a je zložený z podobných plynov vrátane vodíka, hélia a metánu.',
        'uranusText': 'Urán je siedma planéta od Slnka. Nie je viditeľná voľným okom a stala sa prvou planétou objavenou pomocou ďalekohľadu. Urán je prevrátený na svojej strane s axiálnym sklonom 98 stupňov. Často sa to popisuje ako „valenie sa okolo Slnka na jeho boku“.',
        'neptuneText': 'Neptún je ôsmou planétou od Slnka, vďaka čomu je najvzdialenejšou v slnečnej sústave. Tento plynný gigant sa mohol v rannej histórii slnečnej sústavy sformovať oveľa bližšie k Slnku, než sa dostal do svojej súčasnej polohy.',
        // Page About - headings
        'howToUseApplication': 'Ako používať aplikáciu',
        'menuFunctionality': 'Funkcionalita menu',
        'menuSolarSystemModelHeading': 'Model slnečnej sústavy',
        'menuPlanetsHeading': 'Planéty',
        'rightSidebar': 'Pravý bočný panel',
        '3buttons': '3 tlačidlá (v ľavom dolnom rohu)',
        'zoomRangeslider': 'Posúvač na priblíženie modelu',
        'moveModelFunctions': 'Funkcie pre posúvanie modelu',
        'clickOnSceneObjects': 'Klikanie na objekty',
        'sidebarOpenCloseHeading': 'Otvorenie a zatvorenie bočného panelu:',
        'sidebarObjectNamesHeading': 'Mená vesmírnych objektov:',
        'sidebarMoonObjectsHeading': 'Mesiace:',
        'sidebarObjectOrbitsHeading': 'Orbity vesmírnych objektov:',
        'sidebarPlayPauseButtonsHeading': 'Tlačidlo pre zastavenie/spustenie aplikácie:',
        'sidebarConfirmButtonHeading': 'Tlačidlo "Potvrdiť":',
        'cosmicObjectButtonHeading': 'Tlačidlo pre kozmický objekt:',
        'cameraToPlanetButtonHeading': 'Tlačidlo pre kameru:',
        'centerModelButtonHeading': 'Tlačidlo pre vycentrovanie modelu:',
        // Page About - text
        'menuSolarSystemModelInfo': 'V prípade, že je model zobrazený v aktuálnom okne, výberom položky "Model slnečnej sústavy" sa zobrazí upozornenie o strate všetkých nastavených vlastností pre model. Po akceptovaní zmien bude model znovu načítaný do pôvodného stavu. Po zamietnutí zmien ostane otvorený aktuálny model. Otvorenie modelov vo viacerých oknách webového prehliadača bude zamietnuté pre menšie zaťaženie prehliadača.',
        'menuPlanetsInfo': 'Výberom položky "Planéty" sa otvorí nová záložka s ponukou planét. Po výbere a kliknutí na jednu planétu sa zobrazí stránka so stručným popisom a interaktívnym modelom planéty, ktorý je možné ovládať kurzorom.',
        'cosmicObjectButtonInfo': 'Kliknutím na tlačidlo je možné pridať 1 umelý kozmický objekt na orbitu poslednej vybranej planéty. Ak užívateľ zatiaľ neklikol na žiadnu planétu, po aktivácií tlačidla je potrebné vybranú planétu označiť kliknutím na ňu alebo jej orbitu. Pridanie objektu dočasne skryje zobrazené mesiace zvolenej planéty kvôli prehľadnejšiemu zobrazeniu. Počas aktívneho stavu tlačidla sú dočasne nefunkčné funkcie klikania na objekty a zobrazenia ich fyzikálnych vlastností. Aktívne tlačidlo sprístupní posúvač (v hornej časti obrazovky), ktorý slúži na zmenu dráhy kozmického objektu. Je znázornená aj zmena rýchlosti pohybu podľa vzdialenosti objektu od planéty. Deaktiváciu tlačidla je možné previesť pomocou jeho opätovného stlačenia, prejaví sa zmenou farby.',
        'cameraToPlanetButtonInfo': 'Kliknutím na tlačidlo je možné priblížiť kameru na poslednú vybranú planétu. Výber planéty funguje rovnako ako pri tlačidle pre kozmický objekt. Priblíženie kamery ponúka bližší pohľad na vesmírne teleso a jeho mesiace. Narozdiel od priblíženia celého modelu kamera nasleduje zvolený objekt pri rotácii po orbite. Počas aktívneho stavu tlačidla sú prístupné funkcie klikania na objekty a zobrazenia ich fyzikálnych vlastností. Deaktiváciu tlačidla je možné previesť pomocou jeho opätovného stlačenia, prejaví sa zmenou farby.',
        'centerModelButtonInfo': 'Kliknutím na tlačidlo sa posunie model do stredu obrazovky. V prípade ak modelom nebolo pohybované pomocou kurzoru alebo šípok na klávesnici, model ostane na rovnakom mieste. ',
        'zoomRangesliderInfo': 'Priblíženie či zmenšenie modelu je možné previesť pomocou posúvača umiestneného v strede obrazovky dole. Ak bude zvolená veľkosť modelu menšia ako 70%, mesiace planét budú dočasne skryté z dôvodu malej veľkosti modelu.',
        'moveModelFunctionsInfo': 'Pohybovanie modelu je možné spraviť pomocou kliknutia na ľubovoľné miesto obrazovky (okrem objektov modelu) a potiahnutím pomocou kurzoru. Ďalšou možnosťou je využitie šípok na klávesnici. Vrátenie modelu na pôvodnú pozíciu je možné pomocou tlačidla na vycentrovanie modelu alebo klávesou Escape.',
        'clickOnSceneObjectsInfo': 'Model je rozšírený o možnosť klikania na jednotlivé planéty, mesiace alebo ich orbity. Kliknutím na vesmírny objekt alebo jeho orbitu sa v ľavej časti obrazovky zobrazí tabuľka s vybranými fyzikálnymi vlastnosťami a údajmi o zvolenom telese. Pre odlíšenie je vybraný objekt aj jeho orbita farebne odlíšený. Údaje v tabuľke sú dostupné len na čítanie, tabuľka je doplnená o info bubliny pre vysvetlenie vybraných fyzikálnych vlastností, ktoré reagujú na umiestnenie kurzora nad nimi. Zatvorenie tabuľky je možné pomocou kliknutia na ľubovoľné miesto v tabuľke.',
        'sidebarOpenCloseInfo': 'Ovládanie funguje pomocou ikony umiestnenej nad panelom. Kliknutím na ikonu sa panel zatvorí/otvorí.',
        'sidebarObjectNamesInfo': 'Pre zobrazenie len 1 mena pre planétu alebo mesiac je potrebné zrušiť možnosť zobrazenia všetkých mien, vybrať z ponuky konkrétne meno a potvrdiť voľbu tlačidlom "Potvrdiť".',
        'sidebarMoonObjectsInfo': 'V ponuke sú možnosti zobrazenia všetkých mesiacov, skrytie všetkých mesiacov alebo zobrazenie mesiacov pre zvolenú planétu. Zobrazenie mien a orbít mesiacov závisí od ostatných volieb v bočnom paneli. Voľbu je potrebné potvrdiť tlačidlom "Potvrdiť". Mesiace môžu byť zobrazené len do veľkosti modelu, ktorý je priblížený na minimálne 70%.',
        'sidebarObjectOrbitsInfo': 'Pre zobrazenie len 1 orbity pre planétu alebo mesiac je potrebné zrušiť možnosť zobrazenia všetkých orbít, vybrať z ponuky konkrétnu planétu alebo mesiac, pre ktorú bude zobrazená orbita a potvrdiť voľbu tlačidlom "Potvrdiť".',
        'sidebarPlayPauseButtonsInfo': 'Tlačidlo zastaví pohyb planét a mesiacov na orbitách. Ostatné funkcie sú stále prístupné aj počas pozastavenia pohybu vesmírnych objektov.',
        'sidebarConfirmButtonInfo': 'Tlačidlo slúži na potvrdenie a prevedenie všetkých zvolených možností v bočnom paneli. Po jeho stlačení bude tlačidlo dočasne nefunkčné, kým sa prevedú všetky zmeny.'
    }
}

$(function() {
    // First set current language to CZ
    var currentLang = (localStorage.getItem('lang') === '' || localStorage.getItem('lang') === null) ?
        $('html').attr('lang') : localStorage.getItem('lang');
    highlightChosenLanguage(currentLang);

    $('.lang').each(function() {
        $(this).text(arrLang[currentLang][$(this).attr('data-lang')]);
    });

    // Translate to chosen language
    $('.translate').click(function() {
        currentLang = $(this).attr('id');
        localStorage.setItem('lang', currentLang);

        $('.lang').each(function() {
            $(this).text(arrLang[currentLang][$(this).attr('data-lang')]);
        });

        // Translate moon name (and show it after "Play")
        modelScene.sidebarManager.showHideSingleMoonNameOnScene(
            modelScene.sidebarManager.getMoonNamesOnScene(), modelScene.sidebarManager.getTranslatedMoonNames())
    });
})